version: 0.1.0   

name: voting-app-react
description: 'The Stack elimates the boilerplate code required to create,build and deploy the demo voting application'

branding:
  icon: 'cloud'
  color: 'blue'

inputs:

  - name: AZURE_CLIENT_ID
    description: Enter your Azure AD app client ID. To know more about acquiring this key, read https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure. This will be stored as a secret
    is-secret: true
    required: true
    
  - name: AZURE_TENANT_ID
    description: Enter your Azure AD app teanant ID. To know more about acquiring this key, read https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure. This will be stored as a secret
    is-secret: true
    required: true

  - name: AZURE_SUBSCRIPTION_ID
    description: Enter your Azure subscription ID. To know more about acquiring this key, read https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure. This will be stored as a secret
    is-secret: true
    required: true

  - name: AZURE_AKS_RESOURCE_GROUP
    description: Enter the AKS resource group in which this cluster is created
    is-secret: true
    required: true

  - name: AZURE_AKS_NAME
    description: Enter the AKS service name
    is-secret: true
    required: true

  - name: AKS_KUBECONFIG
    description: Enter the kubeconfig JSON token. Read readme.md to discover how to generate this token using CLI
    is-secret: true
    required: true

  - name: ACR_NAME
    description: Enter Azure container registry name
    is-secret: true
    required: true

  - name: ACR_RESOURCE_GROUP
    description: Enter Azure container registry resource group
    is-secret: true
    required: true
    
  - name: BACKEND_URL
    description: Most likely the value will be https://<DNS__NAME>
    is-secret: true
    required: true
    
  - name: DNS_NAME
    description: DNS Name
    is-secret: true
    required: true
    
  - name: AZURE_LOCATION  
    description: A region 'Name', where the new resources will be created. Execute the command 'az account list-locations -o table' to know more about other valid regions.
    default: "centralindia"
    is-secret: true
    required: true
    
configs:
   repo-metadata:
      parameters:
        description: 'Azure service principal'
        secrets: 
        - name: AZURE_CLIENT_ID
          value: ${{inputs.AZURE_CLIENT_ID}}
        - name: AZURE_TENANT_ID
          value: ${{inputs.AZURE_TENANT_ID}}
        - name: AZURE_SUBSCRIPTION_ID
          value: ${{inputs.AZURE_SUBSCRIPTION_ID}}        
        - name: ACR_NAME
          value: ${{inputs.ACR_NAME}}
        - name: ACR_RESOURCE_GROUP
          value: ${{inputs.ACR_RESOURCE_GROUP}}
        - name: AZURE_LOCATION
          value: ${{inputs.AZURE_LOCATION}}
        - name: AZURE_AKS_RESOURCE_GROUP
          value: ${{inputs.AZURE_AKS_RESOURCE_GROUP}}
        - name: AZURE_AKS_NAME
          value: ${{inputs.AZURE_AKS_NAME}}
        - name: AKS_KUBECONFIG
          value: ${{inputs.AKS_KUBECONFIG}}
        - name: BACKEND_URL
          value: ${{inputs.BACKEND_URL}}
        - name: DNS_NAME
          value: ${{inputs.DNS_NAME}}
        - name: AZURE_LOCATION
          value: ${{inputs.AZURE_LOCATION}}
        
          
        topics:
        - react
        - reactjs
        - voting-app
        - azure
        - aks
        - azure-kubernetes--service
        - azure-react-app
        
   environments:                                        
    - name: development
      parameters: 
        protected-branches: false
        allowed-branch-rules:
          - main
          - releases/*
