apiVersion: v1
kind: Service
metadata:
    name: "frontend-react-voting"
    labels:
        app: "frontend-react-voting"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "frontend-react-voting"
